# Generated by Django 5.1.1 on 2024-09-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="author_email",
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="books",
            name="author",
            field=models.CharField(default=1, max_length=130),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="books",
            name="name",
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
