# Generated by Django 5.1.1 on 2024-09-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0003_modela_modelb"),
    ]

    operations = [
        migrations.AddField(
            model_name="modela",
            name="name",
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
